server:
  port: 8088
spring:
  jpa:
    database: mysql
    show-sql: true

#    hibernate:
#      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: dk990807

jackson:
  serialization:
    indent_output: true

flowable:
  async-executor-activate: false
  database-schema-update: true